# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'IteamDetails' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IteamDetails
    pod 'Cosmos', '~> 23.0'

  target 'IteamDetailsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IteamDetailsUITests' do
    # Pods for testing
  end

end
